[package]
name = "document"
version = "0.0.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[features]
lsp = ["dep:tower-lsp", "text/lsp"]

[dependencies]
ast = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }
text = { workspace = true }
thiserror.workspace = true
tower-lsp = { workspace = true, optional = true }
