[package]
name = "schema-store"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
ahash = { workspace = true }
ast = { workspace = true }
dashmap = { workspace = true }
document = { workspace = true }
document-tree = { workspace = true }
glob = { workspace = true }
indexmap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
text = { workspace = true }
tracing = { workspace = true }
url = "2.5.4"

[dev-dependencies]
pretty_assertions = { workspace = true }
