breaking-change:
  - "BREAKING CHANGE:"
  - "BREAKING CHANGE(.*):"

enhancement:
  - "feat:"
  - "feat(.*):"

bug:
  - "fix:"
  - "fix(.*):"

dependencies:
  - "chore(deps):"
  - "chore(deps-dev):"
  - "chore(dependencies):"

documentation:
  - "docs:"
  - "docs(.*):"

style:
  - "style:"
  - "style(.*):"

refactor:
  - "refactor:"
  - "refactor(.*):"

test:
  - "test:"
  - "test(.*):"

ci:
  - "ci:"
  - "ci(.*):"
