[package]
name = "toml-test"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "decode"
path = "bin/decode.rs"

[dependencies]
anyhow = { workspace = true }
ast = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap.workspace = true
document-tree = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
parser = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
text = { workspace = true }
toml-version = { workspace = true }

[dev-dependencies]
pretty_assertions.workspace = true
textwrap.workspace = true
