id = "tombi"
name = "Tombi"
version = "0.1.0"
description = "🦅  TOML Language Server"
schema_version = 1
authors = ["yassun7010 <yassun7010@outlook.com>"]
repository = "https://github.com/tombi-toml/tombi"

[language_servers.toml]
name = "Tombi"
languages = ["TOML"]

[grammars.toml]
repository = "https://github.com/tree-sitter/tree-sitter-toml"
commit = "342d9be207c2dba869b9967124c679b5e6fd0ebe"
