[workspace]
resolver = "2"
members = ["core/*", "crates/*", "xtask"]

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["yassun7010 <yassun7010@outlook.com>"]
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.89"
assert_matches = "1.5.0"
ast = { path = "crates/ast" }
clap = { version = "4.5.20", features = ["derive"] }
either = "1.13.0"
formatter = { path = "crates/formatter" }
itertools = "0.13.0"
logos = "0.14.2"
parser = { path = "crates/parser" }
proc-macro2 = "1.0.87"
quote = "1.0.37"
rowan = "0.15.16"
rstest = "0.23.0"
schemars = "0.8.21"
serde = { version = "^1.0.0", features = ["derive"] }
syntax = { path = "crates/syntax" }
text-size = "1.1.1"
thiserror = "1.0.64"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
