[workspace]
resolver = "2"
members = ["core/*", "crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["yassun7010 <yassun7010@outlook.com>"]
license = "MIT"

[workspace.dependencies]
serde = { version = "^1.0.0", features = ["derive"] }
schemars = "0.8.21"
thiserror = "1.0.64"
rowan = "0.15.16"
logos = "0.14.2"
