[workspace]
resolver = "2"
members = ["rust/*"]

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["yassun7010 <yassun7010@outlook.com>"]
license = "MIT"

[workspace.dependencies]
thiserror = "1.0.64"
