# begin dangling comment1
# begin dangling comment2

# table leading comment1
# table leading comment2
[aaaa]
# table leading comment1
# table leading comment2
[aaaa.bbb]
bool1 = true
bool2 = false
dec = 1  # dec tailing comment
bin = 0b01  # bin tailing comment
oct = 0o01  # oct tailing comment
hex = 0x01  # hex tailing comment
float1 = 0.1234  # float tailing comment
infa = inf
bs = "2"  # bs tailing comment
ls = '3'  # ls tailing comment
array1 = [
    # array begin dangling comment1
    # array begin dangling comment2

    # value1 leading comment1
    # value1 leading comment2
    # value1 leading comment3
    { key3 = 12, key4 = 2024-01-01T10:10:00 }
    # value1 comma leading comment1
    # value1 comma leading comment2
    # value1 comma leading comment3
    ,  # value1 comma tailing comment
    { key3 = 11, key4 = 2024-01-01T10:10:00 },

    # array end dangling comment1
    # array end dangling comment2
  ]  # array tailing comment
array2 = [1, 2, 3]
array3 = [
    1,
    2,
    3,
  ]
array4 = [[
    1,
    2,
    3,
  ], [1, 2, 3]]
date = 2024-01-01  # date tailing comment
time = 10:11:00  # time tailing comment
odt1 = 1979-05-27T07:32:00Z  # odt1 tailing comment
odt2 = 1979-05-27T00:32:00-07:00  # odt2 tailing comment
odt3 = 1979-05-27T00:32:00.999999-07:00  # odt3 tailing comment
odt4 = 1979-05-27 07:32:00Z  # odt4 tailing comment
ldt1 = 1979-05-27T07:32:00  # ldt1 tailing comment
ldt2 = 1979-05-27T00:32:00.999999  # ldt2 tailing comment
ld1 = 1979-05-27  # ld1 tailing comment
lt1 = 07:32:00  # lt1 tailing comment
# lt2 leading tailing comment
lt2 = 00:32:00.999999  # lt2 tailing comment

[aaaa.ccc]
key1 = 11
key2 = "22"

[bbb]
key5 = true

[ddd.eee]  # header tailing comment
key5 = true

[[ffff.ggg]]
key6 = 1

[[ffff.ggg]]
key6 = 2

[[ffff.ggg]]  # header tailing comment
# key value leading comment1
# key value leading comment2
key6 = 3  # key value tailing comment

# end dangling comment1
# end dangling comment2
