[aaaa]
[aaaa.bbb]
key1 = 1  # comment
key2 = "2"
array1 = [{ key3 = 12, key4 = 2024-01-01T10:10:00 }]
date = 2024-01-01
time = 10:11:00
odt1 = 1979-05-27T07:32:00Z
odt2 = 1979-05-27T00:32:00-07:00
odt3 = 1979-05-27T00:32:00.999999-07:00
odt4 = 1979-05-27 07:32:00Z
ldt1 = 1979-05-27T07:32:00
ldt2 = 1979-05-27T00:32:00.999999
ld1 = 1979-05-27
lt1 = 07:32:00
lt2 = 00:32:00.999999

[aaaa.ccc]
key1 = 11
key2 = "22"

[bbb]
key5 = true

[ddd.eee]  # header tailing comment
key5 = true

[[ffff.ggg]]
key6 = 1

[[ffff.ggg]]
key6 = 2

[[ffff.ggg]]
key6 = 2

[[ffff.ggg]]
key6 = 2

[[ffff.ggg]]
key6 = 2

[[ffff.ggg]]
key6 = 2

[[ffff.ggg]]
# key value leading comment2
key6 = 2

[[ffff.ggg]]  # header tailing comment
# key value leading comment1
# key value leading comment2
key6 = 2  # key value tailing comment

# last comment1
# last comment2
