# Tombi config for this project.
#
# This file is for checking if the JsonSchema is correct.
#

toml-version = "v1.0.0"

[format]
line-width = 80
line-ending = "lf"

[lint]

[server]
completion = true

[[schemas]]
path = "tombi.schema.json"
include = ["tombi.toml"]

[[schemas]]
path = "schemas/cargo.schema.json"
include = ["Cargo.toml"]

[[schemas]]
path = "schemas/toml-v1.1.0-preview.schema.json"
include = ["sample.toml"]
