# Tombi config for this project.
#
# This file is for checking if the JsonSchema is correct.
#

toml-version = "v1.0.0"
exclude = ["node_modules/**/*"]
lsp.document-link.enabled = true  # You can convert Inline Table and Dotted Key to each other using Code Action.

[format]

[lint]
[lint.rules]
key-empty = "warn"

# [lsp]
# document-link.enabled = true

[schema]
enabled = true
catalog = {
  paths = [
    "tombi:///json/catalog.json",
    "https://json.schemastore.org/api/json/catalog.json",
  ],
}

[[schemas]]
path = "schemas/type-test.schema.json"
include = ["type-test.toml"]
