# Tombi config for this project.
#
# This file is for checking if the JsonSchema is correct.
#

toml-version = "v1.0.0"

[format]

[lint]

[server]

[schema.catalog]

[[schemas]]
path = "tombi.schema.json"
include = ["tombi.toml"]

[[schemas]]
path = "schemas/cargo.schema.json"
include = ["Cargo.toml"]

[[schemas]]
path = "schemas/type-test.schema.json"
include = ["type-test.toml"]
