# Tombi config for this project.
#
# This file is for checking if the JsonSchema is correct.
#

toml-version = "v1.1.0-preview"

[format]
line-ending = "lf"

[lint]
use-schema-catalog = false

[[schemas]]
path = "tombi.schema.json"
include = ["tombi.toml"]

[[schemas]]
path = "schemas/cargo.schema.json"
include = ["Cargo.toml"]
