[package]
name = "toml-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "toml"
path = "src/main.rs"

[dependencies]
clap.workspace = true
formatter.workspace = true
thiserror.workspace = true
