[package]
name = "tombi-linter"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
futures.workspace = true
itertools.workspace = true
parser = { workspace = true }
regex.workspace = true
schema-store.workspace = true
schemars = { workspace = true }
serde = { workspace = true }
syntax = { workspace = true }
thiserror = { workspace = true }
tombi-ast = { workspace = true }
tombi-config = { workspace = true }
tombi-diagnostic = { workspace = true }
tombi-document-tree = { workspace = true }
tombi-text = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
validator.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
test-lib.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber.workspace = true
