[package]
name = "xtask"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
thiserror.workspace = true
ungrammar = "1.16.1"
