[package]
name = "config"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
clap = ["dep:clap"]

[dependencies]
schemars.workspace = true
serde.workspace = true
clap = {workspace = true, optional = true }
