[package]
name = "tombi-json-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
indexmap = "2.0"
thiserror = "1.0"
tombi-json-lexer = { path = "../tombi-json-lexer" }
tombi-json-syntax = { path = "../tombi-json-syntax" }
tombi-json-tree = { path = "../tombi-json-tree" }
tombi-json-value = { path = "../tombi-json-value" }
tombi-text = { path = "../tombi-text" }
