[package]
name = "tombi-cli"
version = "0.0.1"
authors = ["yassun7010 <yassun7010@outlook.com>"]
edition = "2021"
description = "Tombi CLI"
repository = "https://github.com/tombi-toml/tombi"
license = "MIT"

[dependencies]
