[package]
name = "serde_tombi"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
description = "A TOML serialization file format using Tombi."
repository.workspace = true
license.workspace = true

[dependencies]
ast = { workspace = true }
document = { workspace = true }
document-tree = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
parser = { workspace = true }
serde = { workspace = true }
text = { workspace = true }
thiserror = { workspace = true }
toml-version = { workspace = true }
