[package]
name = "parser"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lexer = { path = "../lexer" }
dom = { path = "../dom" }

logos.workspace = true
rowan.workspace = true
thiserror.workspace = true
