[package]
name = "parser"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dom = { workspace = true }
logos = { workspace = true }
rowan = { workspace = true }
syntax = { workspace = true }
thiserror = { workspace = true }
ast = { workspace = true }
drop_bomb = "0.1.5"
