[package]
name = "parser"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ast = { workspace = true }
drop_bomb = "0.1.5"
itertools = { workspace = true }
logos = { workspace = true }
red-green-tree = { workspace = true }
syntax = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
text.workspace = true

[dev-dependencies]
rstest.workspace = true
tracing-subscriber = { workspace = true }
