[package]
name = "x-tombi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
clap = ["dep:clap"]
default = ["clap", "serde"]
jsonschema = ["dep:schemars"]
serde = ["dep:serde"]

[dependencies]
clap = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
