[package]
name = "tombi-json-arena"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
thiserror.workspace = true
tombi-json-lexer.workspace = true
tombi-json-syntax.workspace = true
