[package]
name = "tombi_rowan"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
serde1 = ["serde", "text-size/serde"]

[dependencies]
countme = "3.0.1"
hashbrown = "0.15.0"
rustc-hash = "2.0.0"
serde = {workspace = true, optional = true, default-features = false}
text-size.workspace = true
