[package]
name = "validator"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
document-tree = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }
schema-store = { workspace = true }
text = { workspace = true }
thiserror = { workspace = true }
tombi-diagnostic = { workspace = true }
tracing = { workspace = true }
