[alias]
tombi = "run --quiet --package tombi-cli --bin tombi --"
decoder = "run --quiet --package toml-test --bin decoder --"
jsonschema = "run --package config --bin jsonschema --all-features --"
xtask = "run --package xtask --bin xtask --"
