[package]
name = "document-tree"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ast.workspace = true
chrono.workspace = true
indexmap.workspace = true
itertools.workspace = true
text.workspace = true
thiserror.workspace = true
