[package]
name = "lexer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
syntax.workspace = true
text.workspace = true
thiserror.workspace = true
tracing.workspace = true
