[package]
name = "tombi-cargo-extension"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Tombi extension for Cargo.toml"
repository.workspace = true
license.workspace = true

[dependencies]
cargo_metadata = { workspace = true }
tombi-extension = { workspace = true }
