[package]
name = "text-position"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
lsp = ["tower-lsp"]

[dependencies]
serde = { workspace = true, optional = true }
text = { workspace = true }
tower-lsp = { workspace = true, optional = true }
