[package]
name = "text-position"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
text-size = { workspace = true }
