[project]
name = "tombi"
version = "0.0.1"
description = "Reserved package for tombi"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.urls]
GitHub = "https://github.com/yassun7010/tombi"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.3",
    "ruff>=0.7.4",
]
