[package]
name = "tombi-extension"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tombi-schema-store.workspace = true
tombi-text.workspace = true
tower-lsp.workspace = true
