[package]
name = "tombi-formatter"
version = "0.0.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
itertools = { workspace = true }
parser = { workspace = true }
schema-store = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
syntax = { workspace = true }
text = { workspace = true }
tokio.workspace = true
tombi-ast = { workspace = true }
tombi-ast-editor = { workspace = true }
tombi-config = { workspace = true }
tombi-diagnostic = { workspace = true }
tombi-document-tree = { workspace = true }
tracing = { workspace = true }
unicode-segmentation = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
test-lib = { workspace = true }
textwrap = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true }

[features]
jsonschema = ["dep:schemars", "serde"]
serde = ["dep:serde"]
