[package]
name = "tombi-ast-editor"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ahash = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
parser = { workspace = true }
regex = { workspace = true }
schema-store = { workspace = true }
syntax = { workspace = true }
text = { workspace = true }
thiserror = { workspace = true }
tombi-ast = { workspace = true }
tombi-document-tree = { workspace = true }
toml-version = { workspace = true }
tracing = { workspace = true }
validator = { workspace = true }
x-tombi = { workspace = true }
