[package]
name = "formatter"
version = "0.0.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
dom = { workspace = true }
ast = { workspace = true }
parser = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
syntax = { workspace = true }
thiserror = { workspace = true }
rstest = { workspace = true }

[dev-dependencies]
logos = { workspace = true }
assert_matches = { workspace = true }
