[package]
name = "formatter"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
parser = { path = "../../crates/parser" }
lexer = { path = "../../crates/lexer" }
dom = { path = "../../crates/dom" }

schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
