[package]
name = "ide"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
ast = { workspace = true }
text-size = { workspace = true }
tracing = { workspace = true }
