[package]
name = "tombi-wasm"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook.workspace = true
getrandom = { workspace = true, features = ["wasm_js"] }
itertools.workspace = true
js-sys.workspace = true
log.workspace = true
nu-ansi-term.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_tombi = { workspace = true, default-features = false, features = ["wasm"] }
# serde_tombi = { workspace = true, default-features = false }
tokio = { workspace = true, features = ["macros"] }
tombi-config.workspace = true
tombi-diagnostic.workspace = true
tombi-formatter.workspace = true
tombi-future = { workspace = true, features = ["wasm"] }
tombi-lexer.workspace = true
tombi-schema-store = { workspace = true, features = ["wasm"] }
tombi-url = { workspace = true, features = ["wasm"] }
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-wasm.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
