name: CI Python

on:
  push:
    branches:
      - main
    paths:
      - python/**
      - .github/workflows/ci_python.yml
  pull_request:
    branches:
      - main
    paths:
      - python/**
      - .github/workflows/ci_python.yml
  workflow_dispatch:

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv run ruff format --check
      - run: uv run ruff check --no-fix
      - run: uv run pytest
