name: CI Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUSTUP_MAX_RETRIES: 10

jobs:
  ci-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@9bdad043e88c75890e36ad3bbc8d27f0090dd609
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
