name: CI VSCode Extensions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci-vscode-extensions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pnpm run build
        working-directory: ./editors/vscode
      - run: pnpm run format:check
        working-directory: ./editors/vscode
      - run: pnpm run lint:check
        working-directory: ./editors/vscode
      - run: pnpm run typecheck
        working-directory: ./editors/vscode
      - run: pnpm run test
        working-directory: ./editors/vscode
