name: Release CLI and VSCode Extension

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

env:
  TOMBI_VERSION: ""
  ASSETS: ""
  CC_aarch64-unknown-linux-gnu: aarch64-linux-gnu-gcc
  CC_arm_unknown_linux_gnueabihf: arm-linux-gnueabihf-gcc
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
  CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
  RUSTFLAGS: "-C strip=symbols"

jobs:
  delete-old-dev-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
            name: |
              tombi-cli-0.0.0-*
              tombi-vscode-0.0.0-*

  release-cli-and-vscode:
    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    needs: [delete-old-dev-artifacts]
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            vscode_target: linux-x64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            vscode_target: linux-arm64
          - os: ubuntu-24.04
            target: arm-unknown-linux-gnueabihf
            vscode_target: linux-armhf
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            vscode_target: win32-x64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            vscode_target: win32-arm64
          - os: macos-13
            target: x86_64-apple-darwin
            vscode_target: darwin-x64
          - os: macos-14
            target: aarch64-apple-darwin
            vscode_target: darwin-arm64
      fail-fast: false
    env:
      TOMBI_TARGET: ${{ matrix.target }}
      VSCODE_TARGET: ${{ matrix.vscode_target }}
      GITHUB_REF: ${{ (github.ref) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Update apt repositories
        if: matrix.target == 'arm-unknown-linux-gnueabihf'
        run: sudo apt-get update

      - name: Install ARM target toolchain
        if: matrix.target == 'arm-unknown-linux-gnueabihf'
        run: sudo apt-get install gcc-arm-linux-gnueabihf

      - run: pnpm install && pnpm run build
        working-directory: ./editors/vscode

      - run: which pnpm

      - uses: ./.github/actions/set-version

      - name: Rub xtask dist
        run: cargo xtask dist
        env:
          RUST_BACKTRACE: "1"

      # FIXME: pnpm cannot exec `cargo xtask dist` on windows.
      #        See https://github.com/matklad/xshell/issues/82
      - name: Package VSCode Extension for Windows
        if: matrix.os == 'windows-latest'
        run: npx vsce package --no-dependencies -o "../../dist/tombi-vscode-${{ env.TOMBI_VERSION }}-${{ matrix.vscode_target }}.vsix" --target ${{ matrix.vscode_target }}
        working-directory: ./editors/vscode

      - name: Publish VSCode Extension
        run: npx vsce publish --no-dependencies --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --packagePath "../../dist/tombi-vscode-${{ env.TOMBI_VERSION }}-${{ matrix.vscode_target }}.vsix" --skip-duplicate
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./editors/vscode

      - name: Publish OpenVSX Extension
        run: npx ovsx publish --no-dependencies --pat ${{ secrets.OPEN_VSX_ACCESS_TOKEN }} --packagePath "../../dist/tombi-vscode-${{ env.TOMBI_VERSION }}-${{ matrix.vscode_target }}.vsix" --skip-duplicate
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./editors/vscode
        timeout-minutes: 5

      - name: Upload tombi-cli artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tombi-cli-${{ env.TOMBI_VERSION }}-${{ matrix.target }}.gz
          path: dist/tombi-cli-${{ env.TOMBI_VERSION }}-${{ matrix.target }}.gz

      - name: Upload tombi-cli artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: tombi-cli-${{ env.TOMBI_VERSION }}-${{ matrix.target }}.zip
          path: dist/tombi-cli-${{ env.TOMBI_VERSION }}-${{ matrix.target }}.zip

      - name: Upload tombi-vscode artifacts
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: tombi-vscode-${{ env.TOMBI_VERSION }}-${{ matrix.vscode_target }}.vsix
          path: dist/tombi-vscode-${{ env.TOMBI_VERSION }}-${{ matrix.vscode_target }}.vsix

  check-release-notes:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
    steps:
      - name: Check if release notes exist
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          if gh release view "${{ github.ref_name }}" --json body -q ".body" | grep -q .; then
            echo "Release notes exist for tag ${{ github.ref_name }}"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No release notes found for tag ${{ github.ref_name }}"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  release-notes:
    needs: [release-cli-and-vscode, check-release-notes]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set-version
      - name: Download tombi-cli artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: tombi-cli-${{ env.TOMBI_VERSION }}-*
          path: tombi-cli-artifacts

      - name: Check Directory
        run: tree -L 3

      - name: Find CLI Assets
        id: find_cli_assets
        shell: bash
        run: |
          echo "ASSETS=$(find tombi-cli-artifacts -type f | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Check ASSETS
        run: |
          echo "ASSETS: '${{ env.ASSETS }}'"
          if [ -z "${{ env.ASSETS }}" ]; then
            echo "Error: ASSETS is empty. Aborting release."
            exit 1
          fi
          echo "ASSETS found successfully."

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/') && needs.check-release-notes.outputs.exists == 'false'
        run: |
          gh release create ${{ github.ref_name }} --generate-notes ${{ env.ASSETS }}
