name: Release CLI

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dist-cli:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            code-target: linux-armhf
          - os: macos-13
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-13
            target: aarch64-apple-darwin
            code-target: darwin-arm64
    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      TOMBI_TARGET: ${{ matrix.target }}
      GITHUB_REF: ${{ (github.ref) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build tombi-cli
        run: cargo build --package tombi-cli --release
      - name: Rub xtask dist
        run: cargo xtask dist
