name: Release VSCode Extension

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish_vscode_extension:
    name: Publish VSCode Extension
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run package
      - run: pnpm run publish -- --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
