name: toml-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  toml-test:
    name: Run toml-test (${{ matrix.toml-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toml-version:
          - v1.0.0
          - v1.1.0-preview
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install toml-test
        run: go install github.com/toml-lang/toml-test/cmd/toml-test@latest

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run toml-test
        run: cargo xtask toml-test --toml-version ${{ matrix.toml-version }}
