[package]
name = "tombi"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Reserved package for tombi"
readme = "README.md"
repository = "https://github.com/tombi-toml/tombi"
license.workspace = true

[dependencies]
